# Generated by Django 4.1.5 on 2023-01-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="countertype",
            name="slug",
            field=models.SlugField(default="slug", max_length=100),
            preserve_default=False,
        ),
    ]
