[tool.curlylint]
include = '\.(html)$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.venv
  )/
)
'''

[tool.curlylint.rules]
indent = 4

[tool.interrogate]
fail-under = 100
quiet = false
verbose = 2
whitelist-regex = ["test_.*"]

[tool.isort]
profile = "black"
honor_noqa = true

[tool.pytest.ini_options]
addopts = "--reuse-db"
DJANGO_SETTINGS_MODULE = "config.settings"
norecursedirs = ".* .git .github config deployed_static docker node_modules media scss static templates"
python_files = "test_*.py"

[tool.ruff]
line-length = 120

# Enable Pyflakes `E` and `F` codes by default.
select = ["E", "F"]
ignore = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
per-file-ignores = {}

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10.
target-version = "py310"
